### PR TITLE
Fixes #17102: Add more sles support for our packer build

### PR DESCRIPTION
**Pull request by Fdall**
https://issues.rudder.io/issues/17102

### CODE REVIEW

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by peckpeck** [comment]
a bit useless isn't it ?

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR updated with a new commit

**Comment by Fdall** [comment]
PR rebased

**Pull request merged**
