### PR TITLE
Fixes #6658: Allow a user to snapshot his platform

### PR DESCRIPTION
**Pull request by peckpeck**
http://www.rudder-project.org/redmine/issues/6658

### CODE REVIEW

**Comment by peckpeck** [comment]
PR updated

**Comment by VinceMacBuche** [comment]
@peckpeck This pr needs to be rebased pleeease :)

**Comment by VinceMacBuche** [comment]
After a rebaseit will be ok to me ;)

**Comment by peckpeck** [comment]
PR updated

**Pull request merged**
