### PR TITLE
Fixes #7870: Wrong rsync command breaks centos boxes (no ssh possible)

### PR DESCRIPTION
**Pull request by VinceMacBuche**
https://www.rudder-project.org/redmine/issues/7870

### CODE REVIEW

**Comment by VinceMacBuche** [comment]
miss file moving ... do not merge

**Comment by peckpeck** [comment]
You didn't move the files in /files/ si this won't work properly

**Comment by peckpeck** [comment]
Sorry, I didn't see your comment above

**Comment by VinceMacBuche** [comment]
PR updated

**Comment by peckpeck** [comment]
Good, merging

**Pull request merged**
